apiVersion: v1
kind: Service
metadata:
  name: database
  labels:
    app: database
spec:
  ports:
  - port: 2379
    name: http
  selector:
    app: database
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: database
  labels:
    app: yaobank
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: database
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: database
        version: v1
    spec:
      serviceAccountName: database
      containers:
      - name: database
        image: spikecurtis/yaobank-database:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 2379
        command: ["etcd"]
        args:
          - "-advertise-client-urls" 
          - "http://database:2379"
          - "-listen-client-urls"
          - "http://0.0.0.0:2379"
---
apiVersion: v1
kind: Service
metadata:
  name: summary
  labels:
    app: summary
spec:
  ports:
  - port: 80
    name: http
  selector:
    app: summary
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: summary
  labels:
    app: yaobank
    database: reader
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: envoy-summary
data:
  envoy.yaml: |
    admin:
      access_log_path: /tmp/admin_access.log
      address:
        socket_address:
          protocol: TCP
          address: 127.0.0.1
          port_value: 15000
    static_resources:
      listeners:
      - name: inbound_http
        address:
          socket_address:
            protocol: TCP
            address: 0.0.0.0
            port_value: 8080
        filter_chains:
        - filters:
          - name: envoy.http_connection_manager
            typed_config:
              "@type": type.googleapis.com/envoy.config.filter.network.http_connection_manager.v2.HttpConnectionManager
              stat_prefix: ingress_http
              route_config:
                name: local_route
                virtual_hosts:
                - name: local_service
                  domains: ["summary"]
                  routes:
                  - match:
                      prefix: "/"
                    route:
                      cluster: local_app
                - name: database
                  domains: ["*"]
                  routes:
                  - match:
                      prefix: "/"
                    route:
                      cluster: database
              http_filters:
              - name: envoy.router
      clusters:
      - name: local_app
        connect_timeout: 0.25s
        type: STATIC
        lb_policy: ROUND_ROBIN
        load_assignment:
          cluster_name: local_app
          endpoints:
          - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: 127.0.0.1
                    port_value: 80
      - name: database
        connect_timeout: 0.25s
        type: STRICT_DNS
        # Comment out the following line to test on v6 networks
        dns_lookup_family: V4_ONLY
        lb_policy: ROUND_ROBIN
        load_assignment:
          cluster_name: database
          endpoints:
          - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: database
                    port_value: 2379

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: summary
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: summary
        version: v1
    spec:
      serviceAccountName: summary
      initContainers:
      - name: istio-init
        image: "docker.io/istio/proxy_init:1.0.7"
        args:
        - "-p"
        - "8080"
        - "-u"
        - "1337"
        - "-i"
        - "*"
        - "-b"
        - "80"
        imagePullPolicy: IfNotPresent
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
          privileged: true
      containers:
      - name: summary
        image: spikecurtis/yaobank-summary:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
      - name: envoy
        image: envoyproxy/envoy:v1.10.0
        imagePullPolicy: IfNotPresent
        securityContext:
            privileged: false
            runAsGroup: 1337
            runAsUser: 1337
        volumeMounts:
        - name: envoy-config
          mountPath: /etc/envoy/
          readOnly: true
      volumes:
        - name: envoy-config
          configMap:
            name: envoy-summary

---
apiVersion: v1
kind: Service
metadata:
  name: customer
  labels:
    app: customer
spec:
  ports:
  - port: 80
    name: http
  selector:
    app: customer
  type: NodePort
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: customer
  labels:
    app: yaobank
    summary: reader
---

apiVersion: v1
kind: ConfigMap
metadata:
  name: envoy-customer
data:
  envoy.yaml: |
    admin:
      access_log_path: /tmp/admin_access.log
      address:
        socket_address:
          protocol: TCP
          address: 127.0.0.1
          port_value: 15000
    static_resources:
      listeners:
      - name: inbound_http
        address:
          socket_address:
            protocol: TCP
            address: 0.0.0.0
            port_value: 8080
        filter_chains:
        - filters:
          - name: envoy.http_connection_manager
            typed_config:
              "@type": type.googleapis.com/envoy.config.filter.network.http_connection_manager.v2.HttpConnectionManager
              stat_prefix: ingress_http
              route_config:
                name: local_route
                virtual_hosts:
                - name: summary
                  domains: ["summary"]
                  routes:
                  - match:
                      prefix: "/"
                    route:
                      cluster: summary
                - name: local_service
                  domains: ["*"]
                  routes:
                  - match:
                      prefix: "/"
                    route:
                      cluster: local_app
              http_filters:
              - name: envoy.router
      clusters:
      - name: local_app
        connect_timeout: 0.25s
        type: STATIC
        lb_policy: ROUND_ROBIN
        load_assignment:
          cluster_name: local_app
          endpoints:
          - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: 127.0.0.1
                    port_value: 80
      - name: summary
        connect_timeout: 0.25s
        type: STRICT_DNS
        # Comment out the following line to test on v6 networks
        dns_lookup_family: V4_ONLY
        lb_policy: ROUND_ROBIN
        load_assignment:
          cluster_name: summary
          endpoints:
          - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: summary
                    port_value: 80

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: customer
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: customer
        version: v1
    spec:
      serviceAccountName: customer
      initContainers:
      - name: istio-init
        image: "docker.io/istio/proxy_init:1.0.7"
        args:
        - "-p"
        - "8080"
        - "-u"
        - "1337"
        - "-i"
        - "*"
        - "-b"
        - "80"
        imagePullPolicy: IfNotPresent
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
          privileged: true
      containers:
      - name: customer
        image: spikecurtis/yaobank-customer:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
      - name: envoy
        image: envoyproxy/envoy:v1.10.0
        imagePullPolicy: IfNotPresent
        securityContext:
            privileged: false
            runAsGroup: 1337
            runAsUser: 1337
        volumeMounts:
        - name: envoy-config
          mountPath: /etc/envoy/
          readOnly: true
      volumes:
        - name: envoy-config
          configMap:
            name: envoy-customer
